<?php

if ( ! defined( 'ABSPATH' ) ) {
  exit; // Exit if accessed directly.
}

$zoho_flow_services_config = array (
  array (
    'name' => esc_html__('WordPress.org'),
    'api_path' => 'wordpress-org',
    'class_name' => 'Zoho_Flow_WordPress_org',
    'gallery_app_link' => 'wordpressorg',
    'description' => esc_html__('Connect WordPress.org to Zoho Flow to automatically post your new WordPress posts on your social media handles such as Twitter, get notifications in your team chat for new posts, and create posts for new events scheduled in your event management app.', 'zoho-flow'),
    'icon_file' => 'wordpress.png',
    'class_test' => 'WP_Comment',
    'app_documentation_link' => 'wordpress-org',
    'embed_link' => 'wordpress_org',
    'version' => 'v1',
    'rest_apis' => array (
      array (
        'type' => 'list',
        'path' => '/users',
        'method' => 'get_users',
        'capability' => 'read',
        'schema_method' => 'get_user_schema',
      ),
      array (
        'type' => 'list',
        'path' => '/posts',
        'method' => 'get_posts',
        'capability' => 'read',
        'schema_method' => 'get_post_schema',
      ),
      array(
        'type' => 'list',
        'path' => '/posts/(?\'post_id\'[\\d]+)',
        'method' => 'get_post',
        'capability' => 'read',
        'schema_method' => 'get_post_schema',
      ),
      array(
        'type' => 'create',
        'path' => '/media/new',
        'method' => 'upload_media',
        'capability' => 'read',
      ),
      array(
        'type' => 'create',
        'path' => '/media',
        'method' => 'upload_media_multipart',
        'capability' => 'read',
      ),
      array(
        'type' => 'delete',
        'path' => '/media/(?\'attachment_id\'[\\d]+)',
        'method' => 'remove_media',
        'capability' => 'delete_posts',
      ),
      array(
        'type' => 'list',
        'path' => '/comments',
        'method' => 'get_comments',
        'capability' => 'read',
        'schema_method' => 'get_comment_schema'
      ),
      array (
        'type' => 'list',
        'path' => '/posts/(?\'post_id\'[\\d]+)/comments/webhooks',
        'method' => 'get_webhooks',
        'capability' => 'read',
      ),
      array(
          'type' => 'create',
          'path' => '/posts/(?\'post_id\'[\\d]+)/comments/webhooks',
          'method' => 'create_post_comments_webhook',
          'capability' => 'edit_posts',
      ),
      array(
          'type' => 'delete',
          'path' => '/posts/(?\'post_id\'[\\d]+)/comments/webhooks/(?\'webhook_id\'[\\d]+)',
          'method' => 'delete_webhook',
          'capability' => 'delete_posts',
      ),
      array(
          'type' => 'list',
          'path' => '/(?\'post_type\'[a-zA-Z_]+)/webhooks',
          'method' => 'get_webhooks_for_post',
          'capability' => 'read',
      ),
      array(
          'type' => 'create',
          'path' => '/(?\'post_type\'[a-zA-Z_]+)/webhooks',
          'method' => 'create_webhook_for_post',
          'capability' => 'edit_posts',
      ),
      array(
          'type' => 'delete',
          'path' => '/(?\'post_type\'[a-zA-Z_]+)/webhooks/(?\'webhook_id\'[\\d]+)',
          'method' => 'delete_webhook',
          'capability' => 'delete_posts',
      ),
      array(
          'type' => 'list',
          'path' => '/comments/webhooks',
          'method' => 'get_comments_webhooks',
          'capability' => 'read',
      ),
      array(
          'type' => 'create',
          'path' => '/comments/webhooks',
          'method' => 'create_comments_webhooks',
          'capability' => 'edit_posts',
      ),
      array(
          'type' => 'delete',
          'path' => '/comments/webhooks/(?\'webhook_id\'[\\d]+)',
          'method' => 'delete_webhook',
          'capability' => 'delete_posts',
      ),
      array(
          'type' => 'create',
          'path' => '/users',
          'method' => 'create_user',
          'capability' => 'create_users',
      ),
      array(
          'type' => 'update',
          'path' => '/users/(?\'user_id\'[\\d]+)',
          'method' => 'update_user',
          'capability' => 'edit_users',
      ),
      array(
          'type' => 'create',
          'path' => '/posts/upsert',
          'method' => 'create_post_insert',
          'capability' => 'edit_posts',
      ),
      array(
          'type' => 'create',
          'path' => '/posts',
          'method' => 'create_post',
          'capability' => 'edit_posts',
      ),
      array(
          'type' => 'update',
          'path' => '/posts/(?\'post_id\'[\\d]+)',
          'method' => 'update_post',
          'capability' => 'edit_posts',
      ),
      array(
          'type' => 'list',
          'path' => '/me',
          'method' => 'get_self',
          'capability' => 'read',
      ),
      array(
        'type' => 'list',
        'path' => '/getuser/(?P<user_id>\d+)',
        'method' => 'get_user_by',
        'capability' => 'read',
      ),
      array(
        'type' => 'list',
        'path' => '/getuser/(?P<login>\S+)',
        'method' => 'get_user_by',
        'capability' => 'read',
      ),
      array(
        'type' => 'list',
        'path' => '/getresetpasswordlink/(?\'user_login\'[a-zA-Z_\@]\S+)',
        'method' => 'get_resetpassword_link',
        'capability' => 'read',
      ),
      array(
        'type' => 'list',
        'path' => '/user_meta/(?\'user_id\'[\\d]+)',
        'method' => 'get_userinfo_meta',
        'capability' => 'read',
      ),
      array(
        'type' => 'list',
        'path' => '/post_types',
        'method' => 'get_post_types',
        'capability' => 'read',
      ),
      array(
        'type' => 'list',
        'path' => '/categories',
        'method' => 'get_categories',
        'capability' => 'read',
      ),
      array(
        'type' => 'list',
        'path' => '/tags',
        'method' => 'get_tags',
        'capability' => 'read',
      ),
      array(
        'type' => 'list',
        'path' => '/systeminfo',
        'method' => 'get_system_info',
        'capability' => 'read',
      )
    ),
    'hooks' => array (
      array (
        'action' => 'comment_post',
        'method' => 'process_comment_post',
        'args_count' => 3,
      ),
      array (
        'action' => 'spammed_comment',
        'method' => 'process_spammed_comment',
        'args_count' => 2,
      ),
      array (
        'action' => 'edit_comment',
        'method' => 'process_edit_comment',
        'args_count' => 2,
      ),
      array (
        'action' => 'wp_set_comment_status',
        'method' => 'process_set_comment_status',
        'args_count' => 2,
      ),
      array (
        'action' => 'register_new_user',
        'method' => 'process_user_register',
        'args_count' => 1,
      ),
      array(
          'action' => 'profile_update',
          'method' => 'process_profile_update',
          'args_count' => 2
      ),
      array(
          'action' => 'save_post',
          'method' => 'process_save_post',
          'args_count' => 3
      ),
      array(
          'action' => 'wp_login',
          'method' => 'process_wp_login',
          'args_count' => 2,
      ),
    ),
  ),
  array (
    'name' => esc_html__('Contact Form 7'),
    'api_path' => 'contact-form-7',
    'class_name' => 'Zoho_Flow_Contact_Form_7',
    'gallery_app_link' => 'contact-form-7',
    'description' => esc_html__('Create forms in Contact Form 7 to collect contacts, feedback, or orders. Then integrate Contact Form 7 with other apps using Zoho Flow to store, share, and analyze your form submissions automatically.', 'zoho-flow'),
    'icon_file' => 'contact-form-7.png',
    'class_test' => 'WPCF7_ContactForm',
    'app_documentation_link' => 'contact-form-7',
    'embed_link' => 'contact_form_7',
    'version' => 'v1',
    'rest_apis' => array (
      array (
        'type' => 'list',
        'path' => '/forms',
        'method' => 'get_forms',
        'capability' => 'wpcf7_read_contact_forms',
        'schema_method' => 'get_form_schema',
      ),
      array (
        'type' => 'list',
        'path' => '/forms/(?\'form_id\'[\\d]+)/fields',
        'method' => 'get_fields',
        'capability' => 'wpcf7_read_contact_forms',
        'schema_method' => 'get_field_schema',
      ),
      array (
        'type' => 'list',
        'path' => '/forms/(?\'form_id\'[\\d]+)/webhooks',
        'method' => 'get_webhooks',
        'capability' => 'wpcf7_read_contact_forms',
        'schema_method' => 'get_form_webhook_schema',
      ),
      array (
        'type' => 'create',
        'path' => '/forms/(?\'form_id\'[\\d]+)/webhooks',
        'method' => 'create_webhook',
        'capability' => 'wpcf7_edit_contact_form',
      ),
      array (
        'type' => 'delete',
        'path' => '/forms/(?\'form_id\'[\\d]+)/webhooks/(?\'webhook_id\'[\\d]+)',
        'method' => 'delete_webhook',
        'capability' => 'wpcf7_delete_contact_form',
      ),
      array (
        'type' => 'get',
        'path' => '/files/(?\'filename\'.+)',
        'method' => 'get_file',
        'capability' => 'wpcf7_edit_contact_form',
      ),
    ),
    'hooks' => array (
      array (
        'action' => 'wpcf7_before_send_mail',
        'method' => 'process_form_submission',
        'args_count' => 1,
      ),
    ),
  ),
  array (
    'name' => esc_html__('WPForms'),
    'api_path' => 'wpforms',
    'class_name' => 'Zoho_Flow_WPForms',
    'gallery_app_link' => 'wpforms',
    'description' => esc_html__('Utilize WPForms’s drag-and-drop form builder to create customizable forms for subscriptions, payments, and lead generation. Connect it to Zoho Flow to automatically add your subscriber information to your email marketing platform, add your payment data as new rows in your spreadsheet, and much more.', 'zoho-flow'),
    'icon_file' => 'wpforms.png',
    'class_test' => 'WPForms',
    'app_documentation_link' => 'wpforms',
    'embed_link' => 'wpforms',
    'version' => 'v1',
    'rest_apis' => array (
      array (
        'type' => 'list',
        'path' => '/forms',
        'method' => 'get_forms',
        'capability' => 'manage_options',
        'schema_method' => 'get_form_schema',
      ),
      array (
        'type' => 'list',
        'path' => '/forms/(?\'form_id\'[\\d]+)/fields',
        'method' => 'get_fields',
        'capability' => 'manage_options',
        'schema_method' => 'get_field_schema',
      ),
      array (
        'type' => 'list',
        'path' => '/forms/(?\'form_id\'[\\d]+)/webhooks',
        'method' => 'get_webhooks',
        'capability' => 'manage_options',
        'schema_method' => 'get_form_webhook_schema',
      ),
      array (
        'type' => 'create',
        'path' => '/forms/(?\'form_id\'[\\d]+)/webhooks',
        'method' => 'create_webhook',
        'capability' => 'manage_options',
      ),
      array (
        'type' => 'delete',
        'path' => '/forms/(?\'form_id\'[\\d]+)/webhooks/(?\'webhook_id\'[\\d]+)',
        'method' => 'delete_webhook',
        'capability' => 'manage_options',
      ),
      array (
        'type' => 'get',
        'path' => '/files/(?\'filename\'.+)',
        'method' => 'get_file',
        'capability' => 'manage_options',
      ),
    ),
    'hooks' => array (
      array (
        'action' => 'wpforms_process_complete',
        'method' => 'process_form_submission',
        'args_count' => 4,
      ),
    ),
  ),
  array (
    'name' => esc_html__('Ninja Forms'),
    'api_path' => 'ninja-forms',
    'class_name' => 'Zoho_Flow_Ninja_Forms',
    'gallery_app_link' => 'ninja-forms',
    'description' => esc_html__('Ninja Forms is a beginner-friendly form builder plugin that also provides conditional logic, multistep forms, and file uploads. Integrate Ninja Forms with your favorite apps to get instant notifications in your team chat app, create tasks in your project management application, or add leads to your CRM for new form submissions.', 'zoho-flow'),
    'icon_file' => 'ninja-forms.png',
    'class_test' => 'Ninja_Forms',
    'app_documentation_link' => 'ninja-forms',
    'embed_link' => 'ninja_forms',
    'version' => 'v1',
    'rest_apis' => array (
      array (
        'type' => 'list',
        'path' => '/forms',
        'method' => 'get_forms',
        'capability' => 'manage_options',
        'schema_method' => 'get_form_schema',
      ),
      array (
        'type' => 'list',
        'path' => '/forms/(?\'form_id\'[\\d]+)/fields',
        'method' => 'get_fields',
        'capability' => 'manage_options',
      ),
      array (
        'type' => 'list',
        'path' => '/forms/(?\'form_id\'[\\d]+)/webhooks',
        'method' => 'get_webhooks',
        'capability' => 'manage_options',
        'schema_method' => 'get_form_webhook_schema',
      ),
      array (
        'type' => 'create',
        'path' => '/forms/(?\'form_id\'[\\d]+)/webhooks',
        'method' => 'create_webhook',
        'capability' => 'manage_options',
      ),
      array (
        'type' => 'delete',
        'path' => '/forms/(?\'form_id\'[\\d]+)/webhooks/(?\'webhook_id\'[\\d]+)',
        'method' => 'delete_webhook',
        'capability' => 'manage_options',
      ),
    ),
    'hooks' => array (
      array (
        'action' => 'ninja_forms_after_submission',
        'method' => 'process_form_submission',
        'args_count' => 4,
      ),
    ),
  ),
  array (
    'name' => esc_html__('Formidable Forms'),
    'api_path' => 'formidable-forms',
    'class_name' => 'Zoho_Flow_Formidable_Forms',
    'gallery_app_link' => 'formidable-forms',
    'description' => esc_html__('Build a simple contact form or complex multipage form with conditional logic, calculations, file uploads, and more, using Formidable Forms. You can then integrate it with other apps to automatically upload the forms to your team’s cloud drive, send new submissions to your team’s chat channel, or add contacts to your CRM.', 'zoho-flow'),
    'icon_file' => 'formidable-forms.png',
    'class_test' => 'FrmSettings',
    'app_documentation_link' => 'formidable-forms',
    'embed_link' => 'formidable_forms',
    'version' => 'v1',
    'rest_apis' => array (
      array (
        'type' => 'list',
        'path' => '/forms',
        'method' => 'get_forms',
        'capability' => 'frm_view_forms',
        'schema_method' => 'get_form_schema',
      ),
      array (
        'type' => 'list',
        'path' => '/forms/(?\'form_id\'[\\d]+)/fields',
        'method' => 'get_fields',
        'capability' => 'frm_view_forms',
        'schema_method' => 'get_field_schema',
      ),
      array (
        'type' => 'list',
        'path' => '/forms/(?\'form_id\'[\\d]+)/webhooks',
        'method' => 'get_webhooks',
        'capability' => 'frm_view_forms',
        'schema_method' => 'get_form_webhook_schema',
      ),
      array (
        'type' => 'create',
        'path' => '/forms/(?\'form_id\'[\\d]+)/webhooks',
        'method' => 'create_webhook',
        'capability' => 'frm_edit_forms',
      ),
      array (
        'type' => 'delete',
        'path' => '/forms/(?\'form_id\'[\\d]+)/webhooks/(?\'webhook_id\'[\\d]+)',
        'method' => 'delete_webhook',
        'capability' => 'frm_delete_forms',
      ),
    ),
    'hooks' => array (
      array (
        'action' => 'frm_after_create_entry',
        'method' => 'process_form_submission',
        'args_count' => 3,
      ),
    ),
  ),
  array (
    'name' => esc_html__('Everest Forms'),
    'api_path' => 'everest-forms',
    'class_name' => 'Zoho_Flow_Everest_Forms',
    'gallery_app_link' => 'everest-forms',
    'description' => esc_html__('Everest Forms is a drag-and-drop form builder plugin that’s lightweight, fast, and mobile responsive. Automatically create calendar events from new form submissions, add subscribers to your mailing list, create tickets for complaints received, and more, using Zoho Flow.', 'zoho-flow'),
    'icon_file' => 'everest-forms.png',
    'class_test' => 'EverestForms',
    'app_documentation_link' => 'everest-forms',
    'embed_link' => 'everest_forms',
    'version' => 'v1',
    'rest_apis' => array (
      array (
        'type' => 'list',
        'path' => '/forms',
        'method' => 'get_forms',
        'capability' => 'manage_everest_forms',
        'schema_method' => 'get_form_schema',
      ),
      array (
        'type' => 'list',
        'path' => '/forms/(?\'form_id\'[\\d]+)/fields',
        'method' => 'get_fields',
        'capability' => 'manage_everest_forms',
        'schema_method' => 'get_field_schema',
      ),
      array (
        'type' => 'list',
        'path' => '/forms/(?\'form_id\'[\\d]+)/webhooks',
        'method' => 'get_webhooks',
        'capability' => 'manage_everest_forms',
        'schema_method' => 'get_form_webhook_schema',
      ),
      array (
        'type' => 'create',
        'path' => '/forms/(?\'form_id\'[\\d]+)/webhooks',
        'method' => 'create_webhook',
        'capability' => 'manage_everest_forms',
      ),
      array (
        'type' => 'delete',
        'path' => '/forms/(?\'form_id\'[\\d]+)/webhooks/(?\'webhook_id\'[\\d]+)',
        'method' => 'delete_webhook',
        'capability' => 'manage_everest_forms',
      ),
    ),
    'hooks' => array (
      array (
        'action' => 'everest_forms_process_complete',
        'method' => 'process_form_submission',
        'args_count' => 4,
      ),
    ),
  ),
  array (
    'name' => esc_html__('Elementor Pro'),
    'api_path' => 'elementor',
    'class_name' => 'Zoho_Flow_Elementor',
    'gallery_app_link' => 'elementor-pro',
    'description' => esc_html__('Elementor’s intuitive website builder and 300+ predesigned templates make it easy to build great websites. Integrate it with your favorite apps, and you can automatically send, store, and analyze form responses, contacts, and feedback.', 'zoho-flow'),
    'icon_file' => 'elementor.png',
    'class_test' => 'ElementorPro\Plugin',
    'app_documentation_link' => '',
    'embed_link' => 'elementor',
    'version' => 'v1',
    'rest_apis' => array (
        array (
            'type' => 'list',
            'path' => '/forms',
            'method' => 'get_forms',
            'capability' => 'manage_options',
            'schema_method' => 'get_form_schema',
        ),
        array (
            'type' => 'list',
            'path' => '/forms/(?\'form_id\'[a-zA-Z0-9_]+)/fields',
            'method' => 'get_fields',
            'capability' => 'manage_options',
        ),
        array (
            'type' => 'list',
            'path' => '/forms/(?\'form_id\'[a-zA-Z0-9_]+)/webhooks',
            'method' => 'get_webhooks',
            'capability' => 'manage_options',
            'schema_method' => 'get_form_webhook_schema',
        ),
        array (
            'type' => 'create',
            'path' => '/forms/(?\'form_id\'[a-zA-Z0-9_]+)/webhooks',
            'method' => 'create_webhook',
            'capability' => 'manage_options',
        ),
        array (
            'type' => 'delete',
            'path' => '/forms/(?\'form_id\'[a-zA-Z0-9_]+)/webhooks/(?\'webhook_id\'[\\d]+)',
            'method' => 'delete_webhook',
            'capability' => 'manage_options',
        ),
    ),
    'hooks' => array (
            array (
                'action' => 'elementor_pro/forms/new_record',
                'method' => 'process_form_submission',
                'args_count' => 2,
            ),
        ),
  ),
  array (
    'name' => esc_html__('Ultimate Member'),
    'api_path' => 'ultimate-member',
    'class_name' => 'Zoho_Flow_Ultimate_Member',
    'gallery_app_link' => 'ultimate-member',
    'description' => esc_html__('Ultimate Member’s WordPress plugin makes it a breeze for users to sign up and become members of your website. Easily manage your forms by automating follow-ups for form submissions, contact management, cloud storage, and more, using Zoho Flow.', 'zoho-flow'),
    'icon_file' => 'ultimate-member.png',
    'class_test' => 'UM',
    'app_documentation_link' => '',
    'embed_link' => 'ultimate_member',
    'version' => 'v1',
    'rest_apis' => array (
        array (
            'type' => 'list',
            'path' => '/forms',
            'method' => 'get_forms',
            'capability' => 'manage_options',
            'schema_method' => 'get_form_schema',
        ),
        array (
            'type' => 'list',
            'path' => '/forms/(?\'form_id\'[\\d]+)/fields',
            'method' => 'get_fields',
            'capability' => 'manage_options',
            'schema_method' => 'get_field_schema',
        ),
        array (
            'type' => 'list',
            'path' => '/forms/(?\'form_id\'[\\d]+)/webhooks',
            'method' => 'get_webhooks',
            'capability' => 'manage_options',
            'schema_method' => 'get_form_webhook_schema',
        ),
        array (
            'type' => 'create',
            'path' => '/forms/(?\'form_id\'[\\d]+)/webhooks',
            'method' => 'create_webhook',
            'capability' => 'manage_options',
        ),
        array (
            'type' => 'delete',
            'path' => '/forms/(?\'form_id\'[\\d]+)/webhooks/(?\'webhook_id\'[\\d]+)',
            'method' => 'delete_webhook',
            'capability' => 'manage_options',
        ),
    ),
    'hooks' => array (
          array (
              'action' => 'um_after_save_registration_details',
              'method' => 'process_form_submission',
              'args_count' => 2,
          ),
          array(
              'action' => 'um_after_user_updated',
              'method' => 'um_user_updated',
              'args_count' => 3,
          ),
      ),
  ),
  array (
    'name' => esc_html__('DigiMember'),
    'api_path' => 'digi-member',
    'class_name' => 'Zoho_Flow_Digi_Member',
    'gallery_app_link' => 'digimember',
    'description' => esc_html__('This easy-to-use membership plugin for WordPress lets you build your own automated membership site. Let Zoho Flow automatically add new orders to your spreadsheet, notify you by chat when a new order is made, create new orders from emails received, and more.', 'zoho-flow'),
    'icon_file' => 'digi-member.png',
    'class_test' => 'ncore_Class',
    'app_documentation_link' => '',
    'embed_link' => 'digimember',
    'version' => 'v1',
    'rest_apis' => array (
        array (
            'type' => 'list',
            'path' => '/products',
            'method' => 'get_all_products',
            'capability' => 'manage_options',
        ),
        array (
            'type' => 'list',
            'path' => '/users/(?\'user_id\'[\\d]+)/products',
            'method' => 'get_products_of_user',
            'capability' => 'manage_options',
        ),
        array (
            'type' => 'list',
            'path' => '/orders/(?\'user_id\'[\\d]+)',
            'method' => 'get_user_orders',
            'capability' => 'manage_options',
        ),
        array (
            'type' => 'create',
            'path' => '/orders',
            'method' => 'create_orders',
            'capability' => 'manage_options',
        ),
        array (
            'type' => 'list',
            'path' => '/(?\'post_type\'[a-zA-Z_]+)/webhooks',
            'method' => 'get_webhook_for_order',
            'capability' => 'manage_options',
        ),
        array (
            'type' => 'create',
            'path' => '/(?\'post_type\'[a-zA-Z_]+)/webhooks',
            'method' => 'create_webhook_for_order',
            'capability' => 'manage_options',
        ),
        array (
            'type' => 'delete',
            'path' => '/(?\'post_type\'[a-zA-Z_]+)/webhooks/(?\'webhook_id\'[\\d]+)',
            'method' => 'delete_webhook',
            'capability' => 'manage_options',
        ),
    ),
    'hooks' => array (
          array (
              'action' => 'digimember_purchase',
              'method' => 'digi_purchase',
              'args_count' => 4,
          ),
      ),
  ),
  array (
    'name' => esc_html__('LearnDash'),
    'api_path' => 'learndash',
    'class_name' => 'Zoho_Flow_LearnDash',
    'gallery_app_link' => 'learndash',
    'description' => esc_html__('LearnDash helps you better sell your online courses by providing multiple pricing models, payment gateways, and automatic renewal notifications. Use Zoho Flow to automatically add new users enrolled in your course to your CRM, send customized emails to users who’ve completed quizzes, add users to a specific group, and more.', 'zoho-flow'),
    'icon_file' => 'learndash.png',
    'class_test' => 'Sfwd_Lms',
    'app_documentation_link' => '',
    'embed_link' => 'learndash_lms',
    'version' => 'v1',
    'rest_apis' => array (
      array (
        'type' => 'list',
        'path' => '/courses',
        'method' => 'get_courses',
        'capability' => 'manage_options',
        'schema_method' => 'get_course_schema',
      ),
      array (
        'type' => 'list',
        'path' => '/groups',
        'method' => 'get_groups',
        'capability' => 'manage_options',
        'schema_method' => 'get_group_schema',
      ),
      array (
        'type' => 'create',
        'path' => '/course/(?\'course_id\'[\\d]+)/enroll',
        'method' => 'enroll_user_to_course',
        'capability' => 'manage_options',
      ),
      array (
        'type' => 'create',
        'path' => '/group/(?\'group_id\'[\\d]+)/add_users',
        'method' => 'add_users_to_group',
        'capability' => 'manage_options',
      ),
      array (
        'type' => 'update',
        'path' => '/group/(?\'group_id\'[\\d]+)/remove_users',
        'method' => 'remove_users_from_group',
        'capability' => 'manage_options',
      ),
      array (
        'type' => 'update',
        'path' => '/course/(?\'course_id\'[\\d]+)/remove_user',
        'method' => 'remove_users_from_course',
        'capability' => 'manage_options',
      ),
      array (
        'type' => 'list',
        'path' => '/user/(?\'user_id\'[\\d]+)/courses',
        'method' => 'user_courses',
        'capability' => 'manage_options',
      ),
      array (
        'type' => 'list',
        'path' => '/course/(?\'course_id\'[\\d]+)/quizzes',
        'method' => 'get_quizzes',
        'capability' => 'manage_options',
      ),
      array (
        'type' => 'list',
        'path' => '/group/(?\'group_id\'[\\d]+)/users',
        'method' => 'group_users',
        'capability' => 'manage_options',
      ),
      array (
        'type' => 'list',
        'path' => '/users',
        'method' => 'get_users',
        'capability' => 'read',
        'schema_method' => 'get_user_schema',
      ),
      array (
        'type' => 'list',
        'path' => '/course/(?\'course_id\'[\\d]+)',
        'method' => 'get_courses',
        'capability' => 'read',
      ),
      array (
        'type' => 'list',
        'path' => '/course/(?\'course_id\'[\\d]+)/lessons',
        'method' => 'get_lessons',
        'capability' => 'read',
      ),
      array (
        'type' => 'list',
        'path' => '/lesson/(?\'lesson_id\'[\\d]+)/topics',
        'method' => 'get_topics',
        'capability' => 'read',
      ),
      array (
        'type' => 'list',
        'path' => '/post_types',
        'method' => 'list_post_types',
        'capability' => 'read',
      ),
      array (
        'type' => 'list',
        'path' => '/questions',
        'method' => 'get_ldquestions',
        'capability' => 'read',
      ),
      array (
        'type' => 'list',
        'path' => '/essay_submissions',
        'method' => 'get_essay_submissions',
        'capability' => 'read',
      ),
      array (
        'type' => 'create',
        'path' => '/(?\'action\'.+)/(?\'form_id\'[\\d]+)/webhook',
        'method' => 'create_webhook',
        'capability' => 'manage_options',
      ),
      array (
        'type' => 'delete',
        'path' => '/webhook/(?\'webhook_id\'[\\d]+)',
        'method' => 'delete_webhook',
        'capability' => 'manage_options',
      ),
      array (
        'type' => 'list',
        'path' => '/(?\'action\'.+)/(?\'form_id\'[\\d]+)/webhooks',
        'method' => 'get_webhooks',
        'capability' => 'manage_options',
      ),
      array (
        'type' => 'list',
        'path' => '/webhooks',
        'method' => 'get_all_webhooks',
        'capability' => 'manage_options',
      ),
      array(
        'type' => 'list',
        'path' => '/systeminfo',
        'method' => 'get_system_info',
        'capability' => 'read',
      )
    ),
    'hooks' => array (
        array (
        'action' => 'learndash_course_completed',
        'method' => 'process_course_completed',
        'args_count' => 1,
      ),
      array(
        'action' => 'learndash_topic_completed',
        'method' => 'process_topic_completed',
        'args_count' => 1
      ),
      array(
        'action' => 'learndash_lesson_completed',
        'method' => 'process_lesson_completed',
        'args_count' => 1
      ),
      array(
        'action' => 'learndash_quiz_completed',
        'method' => 'process_quiz_completed',
        "args_count" => 2
      ),
      array(
        'action' => 'learndash_new_essay_submitted',
        'method' => 'process_essay_submitted',
        "args_count" => 2
      ),
      array(
        'action' => 'learndash_update_course_access',
        'method' => 'process_enrolled_into_course',
        "args_count" => 4

      ),
      array(
        'action' => 'ld_added_group_access',
        'method' => 'process_group_enrolled',
        'args_count'=> 2
      )
    ),
  ),
  array (
    'name' => esc_html__("PlanSo Forms"),
    'api_path' => 'planso-forms',
    'class_name' => 'Zoho_Flow_Planso_Forms',
    'gallery_app_link' => 'planso-forms',
    'description' => esc_html__('PlanSo Forms’s intuitive and user-friendly interface, added with features like auto-responder emails and integrated spam protection, makes it easy to build amazing forms for your WordPress site. Manage form submissions and analyze data efficiently by automatically moving data between your apps using Zoho Flow.', 'zoho-flow'),
    'icon_file' => 'planso-forms.png',
    'class_test' => 'Recursive_ArrayAccess',
    'app_documentation_link' => '',
    'embed_link' => 'planso_forms',
    'version' => 'v1',
    'rest_apis' => array(
        array(
            'type' => 'list',
            'path' => '/forms',
            'method' => 'get_forms',
            'capability' => 'manage_options',
        ),
        array(
            'type' => 'list',
            'path' => '/forms/(?\'form_id\'[\\d]+)/fields',
            'method' => 'get_fields',
            'capability' => 'manage_options',
        ),
        array (
            'type' => 'list',
            'path' => '/forms/(?\'form_id\'[\\d]+)/webhooks',
            'method' => 'get_webhooks',
            'capability' => 'manage_options',
        ),
        array (
            'type' => 'create',
            'path' => '/forms/(?\'form_id\'[\\d]+)/webhooks',
            'method' => 'create_webhook',
            'capability' => 'manage_options',
        ),
        array(
            'type' => 'delete',
            'path' => '/webhooks/(?\'webhook_id\'[\\d]+)',
            'method' => 'delete_webhook',
            'capability' => 'delete_posts',
        ),
    ),
    'hooks' => array(
          array(
              'action' => 'psfb_submit_after_error_check_success',
              'method' => 'process_form_submission',
              'args_count' => 1,
          ),
      ),
  ),
  array (
    'name' => esc_html__('Simple Membership'),
    'api_path' => 'simple-membership',
    'class_name' => 'Zoho_Flow_Simple_Membership',
    'gallery_app_link' => 'simple-membership',
    'description' => esc_html__('With Simple Membership, protect your WordPress posts and pages, restricting access only to members. Integrate Simple Membership with the other apps you use to automatically update membership levels in your CRM, notify members about expiration through various platforms, or even send out personalized member-only offers.', 'zoho-flow'),
    'icon_file' => 'simple-membership.png',
    'class_test' => 'SimpleWpMembership',
    'app_documentation_link' => '',
    'embed_link' => 'simple_membership',
    'version' => 'v1',
    'rest_apis' => array (
      array (
        'type' => 'list',
        'path' => '/members',
        'method' => 'get_members',
        'capability' => 'manage_options',
      ),
      array (
        'type' => 'list',
        'path' => '/membershiplevels',
        'method' => 'get_membership_levels',
        'capability' => 'manage_options',
      ),
      array(
        'type' => 'create',
        'path' => '/create_membership_level',
        'method' => 'create_membership',
        'capability' => 'manage_options',
      ),
      array(
        'type' => 'update',
        'path' => '/update_membership_level',
        'method' => 'update_membership',
        'capability' => 'manage_options',
      ),
      array (
        'type' => 'create',
        'path' => '/createmember',
        'method' => 'create_member',
        'capability' => 'manage_options',
      ),
      array (
        'type' => 'update',
        'path' => '/updatemember',
        'method' => 'update_member',
        'capability' => 'manage_options',
      ),
      array (
        'type' => 'list',
        'path' => '/getmember/(?\'member_id\'[\\d]+)',
        'method' => 'get_member',
        'capability' => 'manage_options',
      ),
      array(
        'type' => 'list',
        'path' => '/getmember/(?P<login>\S+)',
        'method' => 'get_member',
        'capability' => 'read',
      ),
      array(
        'type' => 'list',
        'path' => '/(?\'type\'[a-zA-Z_]+)/webhooks',
        'method' => 'get_webhooks',
        'capability' => 'read',
      ),
      array(
        'type' => 'create',
        'path' => '/(?\'type\'[a-zA-Z_]+)/webhooks',
        'method' => 'create_webhook',
        'capability' => 'edit_posts',
      ),
      array(
        'type' => 'delete',
        'path' => '/webhooks/(?\'webhook_id\'[\\d]+)',
        'method' => 'delete_webhook',
        'capability' => 'delete_posts',
      ),
      array(
        'type' => 'update',
        'path' => '/updatemembershiplevel',
        'method' => 'update_membership_level_of_member',
        'capability' => 'manage_options',
      ),
    ),
    'hooks' => array (
      array(
        'action' => 'swpm_admin_end_registration_complete_user_data',
        'method' => 'process_swpm_registration_user_data',
        'args_count' => 1,
      ),
      array(
        'action' => 'swpm_admin_end_edit_complete_user_data',
        'method' => 'process_swpm_registration_user_data',
        'args_count' => 1,
      )
    )
  ),
  array (
    'name' => esc_html__("Advanced Custom Fields"),
    'api_path' => 'advanced-custom-fields',
    'class_name' => 'Zoho_Flow_Advanced_Custom_Fields',
    'gallery_app_link' => 'advanced-custom-fields',
    'description' => esc_html__('Enhance WordPress with extra content fields like text, images, and more using Advanced Custom Fields. Connect it with Zoho Flow to dynamically update custom field content based on triggers from other apps, or save new content additions to your cloud storage.', 'zoho-flow'),
    'icon_file' => 'acf.png',
    'class_test' => 'ACF',
    'app_documentation_link' => '',
    'embed_link' => 'advanced_custom_fields',
    'version' => 'v1',
    'rest_apis' => array(
      array(
        'type' => 'list',
        'path' => '/fieldgroups',
        'method' => 'get_field_groups',
        'capability' => 'manage_options',
      ),
      array(
        'type' => 'list',
        'path' => '/allfields',
        'method' => 'get_all_fields',
        'capability' => 'manage_options',
      ),
      array(
        'type' => 'list',
        'path' => '/fieldsbygroup/(?\'post_parent\'[\\d]+)',
        'method' => 'get_fields_by_group',
        'capability' => 'manage_options',
      ),
      array(
        'type' => 'list',
        'path' => '/fieldgroup_by_id/(?\'field_group_id\'[\\d]+)',
        'method' => 'get_field_group_by_id',
        'capability' => 'manage_options',
      ),
      array(
        'type' => 'list',
        'path' => '/(?\'form_id\'[\\d]+)/webhooks',
        'method' => 'get_webhooks',
        'capability' => 'read',
      ),
      array(
        'type' => 'create',
        'path' => '/(?\'form_id\'[\\d]+)/webhooks',
        'method' => 'create_webhook',
        'capability' => 'edit_posts',
      ),
      array(
        'type' => 'delete',
        'path' => '/webhooks/(?\'webhook_id\'[\\d]+)',
        'method' => 'delete_webhook',
        'capability' => 'delete_posts',
      ),
      array(
        'type' => 'list',
        'path' => '/fetchfields',
        'method' => 'fetch_fields',
        'capability' => 'manage_options',
      ),
      array(
          'type' => 'update',
          'path' => '/updatefields',
          'method' => 'update_fields',
          'capability' => 'manage_options',
      ),
    ),
    'hooks' => array(
      array(
        'action' => 'acf/save_post',
        'method' => 'process_save_post',
        'args_count' => 1,
      )
    )
  ),
  array (
    'name' => esc_html__("Mailster"),
    'api_path' => 'mailster',
    'class_name' => 'Zoho_Flow_Mailster',
    'gallery_app_link' => 'mailster',
    'description' => esc_html__('Mailster is a comprehensive email newsletter plugin for WordPress. With Mailster integrations, you can automate list management by adding new subscribers from different sources, sending customized follow-up emails based on user behavior, or even updating subscriber info from other platforms.', 'zoho-flow'),
    'icon_file' => 'mailster.png',
    'class_test' => 'MailsterCampaigns',
    'app_documentation_link' => '',
    'embed_link' => 'mailster',
    'version' => 'v1',
    'rest_apis' => array(
      array(
        'type' => 'list',
        'path' => '/campaigns',
        'method' => 'get_campaigns',
        'capability' => 'mailster_dashboard',
      ),
      array(
        'type' => 'list',
        'path' => '/fields',
        'method' => 'get_custom_fields',
        'capability' => 'mailster_dashboard',
      ),
      array(
        'type' => 'list',
        'path' => '/lists',
        'method' => 'get_lists',
        'capability' => 'mailster_dashboard',
      ),
      array(
        'type' => 'list',
        'path' => '/statuses',
        'method' => 'get_statuses',
        'capability' => 'mailster_dashboard',
      ),
      array(
        'type' => 'list',
        'path' => '/subscriber',
        'method' => 'get_subscriber',
        'capability' => 'mailster_manage_subscribers',
      ),
      array(
        'type' => 'create',
        'path' => '/subscriber',
        'method' => 'add_subscriber',
        'capability' => 'mailster_add_subscribers',
      ),
      array(
        'type' => 'update',
        'path' => '/subscriber/(?\'subscriber_id\'[\\d]+)',
        'method' => 'update_subscriber',
        'capability' => 'mailster_edit_subscribers',
      ),
      array(
        'type' => 'create',
        'path' => '/webhooks',
        'method' => 'create_webhook',
        'capability' => 'mailster_manage_subscribers',
      ),
      array(
        'type' => 'delete',
        'path' => '/webhooks/(?\'webhook_id\'[\\d]+)',
        'method' => 'delete_webhook',
        'capability' => 'mailster_manage_subscribers',
      ),
      array(
        'type' => 'list',
        'path' => '/systeminfo',
        'method' => 'get_system_info',
        'capability' => 'read',
      )
    ),
    'hooks' => array (
      array (
        'action' => 'mailster_add_subscriber',
        'method' => 'payload_add_subscriber',
        'args_count' => 1,
      ),
      array (
        'action' => 'mailster_update_subscriber',
        'method' => 'payload_update_subscriber',
        'args_count' => 1,
      ),
      array (
        'action' => 'mailster_tag_added',
        'method' => 'payload_subscriber_tag',
        'args_count' => 3,
      ),
      array (
        'action' => 'mailster_list_added',
        'method' => 'payload_add_subscriber_to_list',
        'args_count' => 3,
      ),

    ),
  ),
  array (
    'name' => esc_html__("Forminator"),
    'api_path' => 'forminator',
    'class_name' => 'Zoho_Flow_Forminator',
    'gallery_app_link' => 'forminator',
    'description' => esc_html__('Use Forminator to create quizzes, polls, and forms on your WordPress site. When connected with Zoho Flow, you can create workflows that automatically compile quiz results in a spreadsheet, inform your team of new poll responses, or create tasks based on form feedback.', 'zoho-flow'),
    'icon_file' => 'forminator.png',
    'class_test' => 'Forminator_API',
    'app_documentation_link' => '',
    'embed_link' => 'forminator',
    'version' => 'v1',
    'rest_apis' => array(
      array(
        'type' => 'list',
        'path' => '/forms',
        'method' => 'get_forms',
        'capability' => 'manage_forminator',
      ),
      array(
        'type' => 'list',
        'path' => '/forms/(?\'form_id\'[\\d]+)/fields',
        'method' => 'get_form_fields',
        'capability' => 'manage_forminator',
      ),
      array(
        'type' => 'list',
        'path' => '/polls',
        'method' => 'get_polls',
        'capability' => 'manage_forminator',
      ),
      array(
        'type' => 'list',
        'path' => '/quizzes',
        'method' => 'get_quizzes',
        'capability' => 'manage_forminator',
      ),
      array(
        'type' => 'list',
        'path' => '/quizzes/(?\'quiz_id\'[\\d]+)/fields',
        'method' => 'get_quiz_fields',
        'capability' => 'manage_forminator',
      ),
      array(
        'type' => 'create',
        'path' => '/webhooks',
        'method' => 'create_webhook',
        'capability' => 'manage_forminator',
      ),
      array(
        'type' => 'delete',
        'path' => '/webhooks/(?\'webhook_id\'[\\d]+)',
        'method' => 'delete_webhook',
        'capability' => 'manage_forminator',
      ),
      array(
        'type' => 'list',
        'path' => '/systeminfo',
        'method' => 'get_system_info',
        'capability' => 'read',
      )
    ),
    'hooks' => array(
      array (
        'action' => 'forminator_custom_form_mail_before_send_mail',
        'method' => 'payload_form_entry_added',
        'args_count' => 4,
      ),
      array (
        'action' => 'forminator_poll_mail_before_send_mail',
        'method' => 'payload_poll_added',
        'args_count' => 4,
      ),
      array (
        'action' => 'forminator_quiz_mail_before_send_mail',
        'method' => 'payload_quiz_added',
        'args_count' => 4,
      )
    )
  ),
  array (
    'name' => esc_html__("GiveWP"),
    'api_path' => 'givewp',
    'class_name' => 'Zoho_Flow_GiveWP',
    'gallery_app_link' => 'givewp',
    'description' => esc_html__('GiveWP is an online donation and fundraising platform for your WordPress website. Build GiveWP integrations on Zoho Flow to instantly notify your team of new donations, generate automated thank-you notes, or even update donor information in your CRM.', 'zoho-flow'),
    'icon_file' => 'givewp.png',
    'class_test' => 'Give_Donate_Form',
    'app_documentation_link' => '',
    'embed_link' => 'givewp',
    'version' => 'v1',
    'rest_apis' => array(
      array(
        'type' => 'list',
        'path' => '/forms',
        'method' => 'get_forms',
        'capability' => 'read_private_give_forms',
      ),
      array(
        'type' => 'list',
        'path' => '/donor',
        'method' => 'get_donor',
        'capability' => 'read_private_give_forms',
      ),
      array(
        'type' => 'create',
        'path' => '/donors/(?\'donor_id\'[\\d]+)/notes',
        'method' => 'add_donor_note',
        'capability' => 'edit_give_forms',
      ),
      array(
        'type' => 'create',
        'path' => '/webhooks',
        'method' => 'create_webhook',
        'capability' => 'read_private_give_forms',
      ),
      array(
        'type' => 'delete',
        'path' => '/webhooks/(?\'webhook_id\'[\\d]+)',
        'method' => 'delete_webhook',
        'capability' => 'read',
      ),
      array(
        'type' => 'list',
        'path' => '/systeminfo',
        'method' => 'get_system_info',
        'capability' => 'read',
      )
    ),
    'hooks' => array(
      array (
        'action' => 'give_donor_post_create',
        'method' => 'payload_donar_added',
        'args_count' => 2,
      ),
      array (
        'action' => 'give_complete_form_donation',
        'method' => 'payload_donation_form_complete',
        'args_count' => 3,
      )
    )
  ),
  array (
    'name' => esc_html__("User Registration"),
    'api_path' => 'user-registration',
    'class_name' => 'Zoho_Flow_User_Registration',
    'gallery_app_link' => 'user-registration',
    'description' => esc_html__('Simplify user signups on your WordPress site with the User Registration plugin. When connected to Zoho Flow, automate onboarding processes by sending welcome emails, adding users to specific groups, or initiating a new member journey in your marketing app.', 'zoho-flow'),
    'icon_file' => 'user-registration.png',
    'class_test' => 'UR_Form_Handler',
    'app_documentation_link' => '',
    'embed_link' => 'user_registration',
    'version' => 'v1',
    'rest_apis' => array(
      array(
        'type' => 'list',
        'path' => '/forms',
        'method' => 'get_forms',
        'capability' => 'manage_user_registration',
      ),
      array(
        'type' => 'list',
        'path' => '/forms/(?\'form_id\'[\\d]+)/fields',
        'method' => 'get_form_fields',
        'capability' => 'manage_user_registration',
      ),
      array(
        'type' => 'create',
        'path' => '/webhooks',
        'method' => 'create_webhook',
        'capability' => 'read_private_give_forms',
      ),
      array(
        'type' => 'delete',
        'path' => '/webhooks/(?\'webhook_id\'[\\d]+)',
        'method' => 'delete_webhook',
        'capability' => 'read',
      ),
      array(
        'type' => 'list',
        'path' => '/systeminfo',
        'method' => 'get_system_info',
        'capability' => 'read',
      )
    ),
    'hooks' => array(
      array (
        'action' => 'user_registration_after_register_user_action',
        'method' => 'payload_after_register_user_action',
        'args_count' => 3,
      )
    )
  ),
  array (
    'name' => esc_html__("Paid Memberships Pro"),
    'api_path' => 'paid-memberships-pro',
    'class_name' => 'Zoho_Flow_Paid_Memberships_Pro',
    'gallery_app_link' => 'paid-memberships-pro',
    'description' => esc_html__('Elevate your membership site with Paid Memberships Pro, offering levels, subscription packages, and more. Connect it with Zoho Flow, to easily handle member renewals, send out reminder emails before expiration, or even promote upgrades based on user activities.', 'zoho-flow'),
    'icon_file' => 'paid-memberships-pro.png',
    'class_test' => 'MemberOrder',
    'app_documentation_link' => '',
    'embed_link' => 'paid_memberships_pro',
    'version' => 'v1',
    'rest_apis' => array(
      array(
        'type' => 'list',
        'path' => '/memberfields',
        'method' => 'get_fields',
        'capability' => 'pmpro_userfields',
      ),
      array(
        'type' => 'list',
        'path' => '/membershiplevels',
        'method' => 'get_levels',
        'capability' => 'pmpro_membershiplevels',
      ),
      array(
        'type' => 'list',
        'path' => '/member',
        'method' => 'get_user',
        'capability' => 'pmpro_memberslist',
      ),
      array(
        'type' => 'create',
        'path' => '/membershiplevelchange',
        'method' => 'change_user_membership_level',
        'capability' => 'pmpro_membershiplevels',
      ),
      array(
        'type' => 'create',
        'path' => '/webhooks',
        'method' => 'create_webhook',
        'capability' => 'read_private_give_forms',
      ),
      array(
        'type' => 'delete',
        'path' => '/webhooks/(?\'webhook_id\'[\\d]+)',
        'method' => 'delete_webhook',
        'capability' => 'read',
      ),
      array(
        'type' => 'list',
        'path' => '/systeminfo',
        'method' => 'get_system_info',
        'capability' => 'read',
      )
    ),
    'hooks' => array(
      array (
        'action' => 'pmpro_added_order',
        'method' => 'payload_order_added',
        'args_count' => 1,
      ),
      array (
        'action' => 'pmpro_updated_order',
        'method' => 'payload_order_updated',
        'args_count' => 1,
      ),
      array (
        'action' => 'pmpro_after_change_membership_level',
        'method' => 'payload_membership_level_changed',
        'args_count' => 3,
      ),
    )
  )
);
